# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    omit_local_variable_types: false # Rule excluded because it makes reasoning about code harder for those that don't know the types returned by various functions.

analyzer:
#   exclude:
#     - path/to/excluded/files/**
